<?xml version="1.0" encoding="utf-8"?><Database Name="AutoResende.DataBase" Class="AutoResendeDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=ThiagoDiniz-PC;Initial Catalog=AutoResende.DataBase;Integrated Security=True" SettingsObjectName="AutoResende.Model.Properties.Settings" SettingsPropertyName="AutoResende_DataBaseConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Cliente" Member="Clientes">
    <Type Name="Cliente">
      <Column Name="idCliente" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Nome" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CPF" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="RG" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="OrgaoExpedidor" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DataNascimento" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Logradouro" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Bairro" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Cidade" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="UF" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CEP" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TelRes" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TelCel" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Comentario" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Pais" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Cliente_OrdemServico" Member="OrdemServicos" ThisKey="CPF" OtherKey="CPF" Type="OrdemServico" />
      <Association Name="Cliente_OrdemServico1" Member="OrdemServicos1" ThisKey="CPF" OtherKey="CPF" Type="OrdemServico" />
    </Type>
  </Table>
  <Table Name="dbo.Veiculo" Member="Veiculos">
    <Type Name="Veiculo">
      <Column Name="idVeiculo" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Marca" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Modelo" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Cor" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Placa" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Descricao" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Combustivel" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Odometro" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Veiculo_OrdemServico" Member="OrdemServicos" ThisKey="Placa" OtherKey="Placa" Type="OrdemServico" />
      <Association Name="Veiculo_OrdemServico1" Member="OrdemServicos1" ThisKey="Placa" OtherKey="Placa" Type="OrdemServico" />
    </Type>
  </Table>
  <Table Name="dbo.Fornecedor" Member="Fornecedors">
    <Type Name="Fornecedor">
      <Column Name="idFornecedor" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NomeFantasia" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="RazaoSocial" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CNPJ" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Logradouro" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Bairro" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Cidade" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="UF" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CEP" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TelRes" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TelCel" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Pais" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Comentario" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="InscricaoEstadual" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Fornecedor_Mercadoria" Member="Mercadorias" ThisKey="CNPJ" OtherKey="CNPJ" Type="Mercadoria" />
    </Type>
  </Table>
  <Table Name="dbo.Funcionario" Member="Funcionarios">
    <Type Name="Funcionario">
      <Column Name="idFuncionario" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Nome" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CPF" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="RG" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="OrgaoExpedidor" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DataNascimento" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Logradouro" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Bairro" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Cidade" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="UF" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CEP" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TelRes" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TelCel" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Pais" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Comentario" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Mercadoria" Member="Mercadorias">
    <Type Name="Mercadoria">
      <Column Name="idMercadoria" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Descricao" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="DescricaoDetalhada" Type="System.String" DbType="VarChar(400)" CanBeNull="true" />
      <Column Name="ValorCusto" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="ValorVenda" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="QuantidadeEstoque" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Marca" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CNPJ" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Fornecedor_Mercadoria" Member="Fornecedor" ThisKey="CNPJ" OtherKey="CNPJ" Type="Fornecedor" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.OrdemServico" Member="OrdemServicos">
    <Type Name="OrdemServico">
      <Column Name="idOrdemServico" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Descricao" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Data" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="DataEntrega" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="idTipoServico" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CPF" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Placa" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Cliente_OrdemServico" Member="Cliente" ThisKey="CPF" OtherKey="CPF" Type="Cliente" IsForeignKey="true" />
      <Association Name="Cliente_OrdemServico1" Member="Cliente1" ThisKey="CPF" OtherKey="CPF" Type="Cliente" IsForeignKey="true" />
      <Association Name="Veiculo_OrdemServico" Member="Veiculo" ThisKey="Placa" OtherKey="Placa" Type="Veiculo" IsForeignKey="true" />
      <Association Name="Veiculo_OrdemServico1" Member="Veiculo1" ThisKey="Placa" OtherKey="Placa" Type="Veiculo" IsForeignKey="true" />
      <Association Name="TipoServico_OrdemServico" Member="TipoServico" ThisKey="idTipoServico" OtherKey="idTipoServico" Type="TipoServico" IsForeignKey="true" />
      <Association Name="TipoServico_OrdemServico1" Member="TipoServico1" ThisKey="idTipoServico" OtherKey="idTipoServico" Type="TipoServico" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TipoServico" Member="TipoServicos">
    <Type Name="TipoServico">
      <Column Name="idTipoServico" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NomeServiço" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Descricao" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Association Name="TipoServico_OrdemServico" Member="OrdemServicos" ThisKey="idTipoServico" OtherKey="idTipoServico" Type="OrdemServico" />
      <Association Name="TipoServico_OrdemServico1" Member="OrdemServicos1" ThisKey="idTipoServico" OtherKey="idTipoServico" Type="OrdemServico" />
    </Type>
  </Table>
</Database>