#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoResende.Model
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="AutoResende.DataBase")]
	public partial class AutoResendeDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCliente(Cliente instance);
    partial void UpdateCliente(Cliente instance);
    partial void DeleteCliente(Cliente instance);
    partial void InsertVeiculo(Veiculo instance);
    partial void UpdateVeiculo(Veiculo instance);
    partial void DeleteVeiculo(Veiculo instance);
    partial void InsertFuncionario(Funcionario instance);
    partial void UpdateFuncionario(Funcionario instance);
    partial void DeleteFuncionario(Funcionario instance);
    partial void InsertMercadoria(Mercadoria instance);
    partial void UpdateMercadoria(Mercadoria instance);
    partial void DeleteMercadoria(Mercadoria instance);
    partial void InsertOrdemServico(OrdemServico instance);
    partial void UpdateOrdemServico(OrdemServico instance);
    partial void DeleteOrdemServico(OrdemServico instance);
    partial void InsertTipoServico(TipoServico instance);
    partial void UpdateTipoServico(TipoServico instance);
    partial void DeleteTipoServico(TipoServico instance);
    partial void InsertFornecedor(Fornecedor instance);
    partial void UpdateFornecedor(Fornecedor instance);
    partial void DeleteFornecedor(Fornecedor instance);
    #endregion
		
		public AutoResendeDataContext() : 
				base(global::AutoResende.Model.Properties.Settings.Default.AutoResende_DataBaseConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public AutoResendeDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AutoResendeDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AutoResendeDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AutoResendeDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Cliente> Clientes
		{
			get
			{
				return this.GetTable<Cliente>();
			}
		}
		
		public System.Data.Linq.Table<Veiculo> Veiculos
		{
			get
			{
				return this.GetTable<Veiculo>();
			}
		}
		
		public System.Data.Linq.Table<Funcionario> Funcionarios
		{
			get
			{
				return this.GetTable<Funcionario>();
			}
		}
		
		public System.Data.Linq.Table<Mercadoria> Mercadorias
		{
			get
			{
				return this.GetTable<Mercadoria>();
			}
		}
		
		public System.Data.Linq.Table<OrdemServico> OrdemServicos
		{
			get
			{
				return this.GetTable<OrdemServico>();
			}
		}
		
		public System.Data.Linq.Table<TipoServico> TipoServicos
		{
			get
			{
				return this.GetTable<TipoServico>();
			}
		}
		
		public System.Data.Linq.Table<Fornecedor> Fornecedors
		{
			get
			{
				return this.GetTable<Fornecedor>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Cliente")]
	public partial class Cliente : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idCliente;
		
		private string _Nome;
		
		private string _CPF;
		
		private string _RG;
		
		private string _OrgaoExpedidor;
		
		private System.DateTime _DataNascimento;
		
		private string _Logradouro;
		
		private string _Bairro;
		
		private string _Cidade;
		
		private string _UF;
		
		private string _CEP;
		
		private string _TelRes;
		
		private string _TelCel;
		
		private string _email;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidClienteChanging(int value);
    partial void OnidClienteChanged();
    partial void OnNomeChanging(string value);
    partial void OnNomeChanged();
    partial void OnCPFChanging(string value);
    partial void OnCPFChanged();
    partial void OnRGChanging(string value);
    partial void OnRGChanged();
    partial void OnOrgaoExpedidorChanging(string value);
    partial void OnOrgaoExpedidorChanged();
    partial void OnDataNascimentoChanging(System.DateTime value);
    partial void OnDataNascimentoChanged();
    partial void OnLogradouroChanging(string value);
    partial void OnLogradouroChanged();
    partial void OnBairroChanging(string value);
    partial void OnBairroChanged();
    partial void OnCidadeChanging(string value);
    partial void OnCidadeChanged();
    partial void OnUFChanging(string value);
    partial void OnUFChanged();
    partial void OnCEPChanging(string value);
    partial void OnCEPChanged();
    partial void OnTelResChanging(string value);
    partial void OnTelResChanged();
    partial void OnTelCelChanging(string value);
    partial void OnTelCelChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    #endregion
		
		public Cliente()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idCliente", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int idCliente
		{
			get
			{
				return this._idCliente;
			}
			set
			{
				if ((this._idCliente != value))
				{
					this.OnidClienteChanging(value);
					this.SendPropertyChanging();
					this._idCliente = value;
					this.SendPropertyChanged("idCliente");
					this.OnidClienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nome", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Nome
		{
			get
			{
				return this._Nome;
			}
			set
			{
				if ((this._Nome != value))
				{
					this.OnNomeChanging(value);
					this.SendPropertyChanging();
					this._Nome = value;
					this.SendPropertyChanged("Nome");
					this.OnNomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CPF", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string CPF
		{
			get
			{
				return this._CPF;
			}
			set
			{
				if ((this._CPF != value))
				{
					this.OnCPFChanging(value);
					this.SendPropertyChanging();
					this._CPF = value;
					this.SendPropertyChanged("CPF");
					this.OnCPFChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RG", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string RG
		{
			get
			{
				return this._RG;
			}
			set
			{
				if ((this._RG != value))
				{
					this.OnRGChanging(value);
					this.SendPropertyChanging();
					this._RG = value;
					this.SendPropertyChanged("RG");
					this.OnRGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrgaoExpedidor", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string OrgaoExpedidor
		{
			get
			{
				return this._OrgaoExpedidor;
			}
			set
			{
				if ((this._OrgaoExpedidor != value))
				{
					this.OnOrgaoExpedidorChanging(value);
					this.SendPropertyChanging();
					this._OrgaoExpedidor = value;
					this.SendPropertyChanged("OrgaoExpedidor");
					this.OnOrgaoExpedidorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataNascimento", DbType="Date NOT NULL")]
		public System.DateTime DataNascimento
		{
			get
			{
				return this._DataNascimento;
			}
			set
			{
				if ((this._DataNascimento != value))
				{
					this.OnDataNascimentoChanging(value);
					this.SendPropertyChanging();
					this._DataNascimento = value;
					this.SendPropertyChanged("DataNascimento");
					this.OnDataNascimentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Logradouro", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Logradouro
		{
			get
			{
				return this._Logradouro;
			}
			set
			{
				if ((this._Logradouro != value))
				{
					this.OnLogradouroChanging(value);
					this.SendPropertyChanging();
					this._Logradouro = value;
					this.SendPropertyChanged("Logradouro");
					this.OnLogradouroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bairro", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Bairro
		{
			get
			{
				return this._Bairro;
			}
			set
			{
				if ((this._Bairro != value))
				{
					this.OnBairroChanging(value);
					this.SendPropertyChanging();
					this._Bairro = value;
					this.SendPropertyChanged("Bairro");
					this.OnBairroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cidade", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Cidade
		{
			get
			{
				return this._Cidade;
			}
			set
			{
				if ((this._Cidade != value))
				{
					this.OnCidadeChanging(value);
					this.SendPropertyChanging();
					this._Cidade = value;
					this.SendPropertyChanged("Cidade");
					this.OnCidadeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UF", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string UF
		{
			get
			{
				return this._UF;
			}
			set
			{
				if ((this._UF != value))
				{
					this.OnUFChanging(value);
					this.SendPropertyChanging();
					this._UF = value;
					this.SendPropertyChanged("UF");
					this.OnUFChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CEP", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string CEP
		{
			get
			{
				return this._CEP;
			}
			set
			{
				if ((this._CEP != value))
				{
					this.OnCEPChanging(value);
					this.SendPropertyChanging();
					this._CEP = value;
					this.SendPropertyChanged("CEP");
					this.OnCEPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TelRes", DbType="VarChar(50)")]
		public string TelRes
		{
			get
			{
				return this._TelRes;
			}
			set
			{
				if ((this._TelRes != value))
				{
					this.OnTelResChanging(value);
					this.SendPropertyChanging();
					this._TelRes = value;
					this.SendPropertyChanged("TelRes");
					this.OnTelResChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TelCel", DbType="VarChar(50)")]
		public string TelCel
		{
			get
			{
				return this._TelCel;
			}
			set
			{
				if ((this._TelCel != value))
				{
					this.OnTelCelChanging(value);
					this.SendPropertyChanging();
					this._TelCel = value;
					this.SendPropertyChanged("TelCel");
					this.OnTelCelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(50)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Veiculo")]
	public partial class Veiculo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idVeiculo;
		
		private string _Modelo;
		
		private string _Cor;
		
		private string _Placa;
		
		private string _Descricao;
		
		private string _Combustivel;
		
		private System.Nullable<int> _Odometro;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidVeiculoChanging(int value);
    partial void OnidVeiculoChanged();
    partial void OnModeloChanging(string value);
    partial void OnModeloChanged();
    partial void OnCorChanging(string value);
    partial void OnCorChanged();
    partial void OnPlacaChanging(string value);
    partial void OnPlacaChanged();
    partial void OnDescricaoChanging(string value);
    partial void OnDescricaoChanged();
    partial void OnCombustivelChanging(string value);
    partial void OnCombustivelChanged();
    partial void OnOdometroChanging(System.Nullable<int> value);
    partial void OnOdometroChanged();
    #endregion
		
		public Veiculo()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idVeiculo", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int idVeiculo
		{
			get
			{
				return this._idVeiculo;
			}
			set
			{
				if ((this._idVeiculo != value))
				{
					this.OnidVeiculoChanging(value);
					this.SendPropertyChanging();
					this._idVeiculo = value;
					this.SendPropertyChanged("idVeiculo");
					this.OnidVeiculoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Modelo", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Modelo
		{
			get
			{
				return this._Modelo;
			}
			set
			{
				if ((this._Modelo != value))
				{
					this.OnModeloChanging(value);
					this.SendPropertyChanging();
					this._Modelo = value;
					this.SendPropertyChanged("Modelo");
					this.OnModeloChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cor", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Cor
		{
			get
			{
				return this._Cor;
			}
			set
			{
				if ((this._Cor != value))
				{
					this.OnCorChanging(value);
					this.SendPropertyChanging();
					this._Cor = value;
					this.SendPropertyChanged("Cor");
					this.OnCorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Placa", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Placa
		{
			get
			{
				return this._Placa;
			}
			set
			{
				if ((this._Placa != value))
				{
					this.OnPlacaChanging(value);
					this.SendPropertyChanging();
					this._Placa = value;
					this.SendPropertyChanged("Placa");
					this.OnPlacaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descricao", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Descricao
		{
			get
			{
				return this._Descricao;
			}
			set
			{
				if ((this._Descricao != value))
				{
					this.OnDescricaoChanging(value);
					this.SendPropertyChanging();
					this._Descricao = value;
					this.SendPropertyChanged("Descricao");
					this.OnDescricaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Combustivel", DbType="VarChar(50)")]
		public string Combustivel
		{
			get
			{
				return this._Combustivel;
			}
			set
			{
				if ((this._Combustivel != value))
				{
					this.OnCombustivelChanging(value);
					this.SendPropertyChanging();
					this._Combustivel = value;
					this.SendPropertyChanged("Combustivel");
					this.OnCombustivelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Odometro", DbType="Int")]
		public System.Nullable<int> Odometro
		{
			get
			{
				return this._Odometro;
			}
			set
			{
				if ((this._Odometro != value))
				{
					this.OnOdometroChanging(value);
					this.SendPropertyChanging();
					this._Odometro = value;
					this.SendPropertyChanged("Odometro");
					this.OnOdometroChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Funcionario")]
	public partial class Funcionario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idFuncionario;
		
		private string _Nome;
		
		private string _CPF;
		
		private string _RG;
		
		private string _OrgaoExpedidor;
		
		private System.DateTime _DataNascimento;
		
		private string _Logradouro;
		
		private string _Bairro;
		
		private string _Cidade;
		
		private string _UF;
		
		private string _CEP;
		
		private string _TelRes;
		
		private string _TelCel;
		
		private string _email;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidFuncionarioChanging(int value);
    partial void OnidFuncionarioChanged();
    partial void OnNomeChanging(string value);
    partial void OnNomeChanged();
    partial void OnCPFChanging(string value);
    partial void OnCPFChanged();
    partial void OnRGChanging(string value);
    partial void OnRGChanged();
    partial void OnOrgaoExpedidorChanging(string value);
    partial void OnOrgaoExpedidorChanged();
    partial void OnDataNascimentoChanging(System.DateTime value);
    partial void OnDataNascimentoChanged();
    partial void OnLogradouroChanging(string value);
    partial void OnLogradouroChanged();
    partial void OnBairroChanging(string value);
    partial void OnBairroChanged();
    partial void OnCidadeChanging(string value);
    partial void OnCidadeChanged();
    partial void OnUFChanging(string value);
    partial void OnUFChanged();
    partial void OnCEPChanging(string value);
    partial void OnCEPChanged();
    partial void OnTelResChanging(string value);
    partial void OnTelResChanged();
    partial void OnTelCelChanging(string value);
    partial void OnTelCelChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    #endregion
		
		public Funcionario()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idFuncionario", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int idFuncionario
		{
			get
			{
				return this._idFuncionario;
			}
			set
			{
				if ((this._idFuncionario != value))
				{
					this.OnidFuncionarioChanging(value);
					this.SendPropertyChanging();
					this._idFuncionario = value;
					this.SendPropertyChanged("idFuncionario");
					this.OnidFuncionarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nome", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Nome
		{
			get
			{
				return this._Nome;
			}
			set
			{
				if ((this._Nome != value))
				{
					this.OnNomeChanging(value);
					this.SendPropertyChanging();
					this._Nome = value;
					this.SendPropertyChanged("Nome");
					this.OnNomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CPF", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string CPF
		{
			get
			{
				return this._CPF;
			}
			set
			{
				if ((this._CPF != value))
				{
					this.OnCPFChanging(value);
					this.SendPropertyChanging();
					this._CPF = value;
					this.SendPropertyChanged("CPF");
					this.OnCPFChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RG", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string RG
		{
			get
			{
				return this._RG;
			}
			set
			{
				if ((this._RG != value))
				{
					this.OnRGChanging(value);
					this.SendPropertyChanging();
					this._RG = value;
					this.SendPropertyChanged("RG");
					this.OnRGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrgaoExpedidor", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string OrgaoExpedidor
		{
			get
			{
				return this._OrgaoExpedidor;
			}
			set
			{
				if ((this._OrgaoExpedidor != value))
				{
					this.OnOrgaoExpedidorChanging(value);
					this.SendPropertyChanging();
					this._OrgaoExpedidor = value;
					this.SendPropertyChanged("OrgaoExpedidor");
					this.OnOrgaoExpedidorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataNascimento", DbType="Date NOT NULL")]
		public System.DateTime DataNascimento
		{
			get
			{
				return this._DataNascimento;
			}
			set
			{
				if ((this._DataNascimento != value))
				{
					this.OnDataNascimentoChanging(value);
					this.SendPropertyChanging();
					this._DataNascimento = value;
					this.SendPropertyChanged("DataNascimento");
					this.OnDataNascimentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Logradouro", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Logradouro
		{
			get
			{
				return this._Logradouro;
			}
			set
			{
				if ((this._Logradouro != value))
				{
					this.OnLogradouroChanging(value);
					this.SendPropertyChanging();
					this._Logradouro = value;
					this.SendPropertyChanged("Logradouro");
					this.OnLogradouroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bairro", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Bairro
		{
			get
			{
				return this._Bairro;
			}
			set
			{
				if ((this._Bairro != value))
				{
					this.OnBairroChanging(value);
					this.SendPropertyChanging();
					this._Bairro = value;
					this.SendPropertyChanged("Bairro");
					this.OnBairroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cidade", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Cidade
		{
			get
			{
				return this._Cidade;
			}
			set
			{
				if ((this._Cidade != value))
				{
					this.OnCidadeChanging(value);
					this.SendPropertyChanging();
					this._Cidade = value;
					this.SendPropertyChanged("Cidade");
					this.OnCidadeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UF", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string UF
		{
			get
			{
				return this._UF;
			}
			set
			{
				if ((this._UF != value))
				{
					this.OnUFChanging(value);
					this.SendPropertyChanging();
					this._UF = value;
					this.SendPropertyChanged("UF");
					this.OnUFChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CEP", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string CEP
		{
			get
			{
				return this._CEP;
			}
			set
			{
				if ((this._CEP != value))
				{
					this.OnCEPChanging(value);
					this.SendPropertyChanging();
					this._CEP = value;
					this.SendPropertyChanged("CEP");
					this.OnCEPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TelRes", DbType="VarChar(50)")]
		public string TelRes
		{
			get
			{
				return this._TelRes;
			}
			set
			{
				if ((this._TelRes != value))
				{
					this.OnTelResChanging(value);
					this.SendPropertyChanging();
					this._TelRes = value;
					this.SendPropertyChanged("TelRes");
					this.OnTelResChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TelCel", DbType="VarChar(50)")]
		public string TelCel
		{
			get
			{
				return this._TelCel;
			}
			set
			{
				if ((this._TelCel != value))
				{
					this.OnTelCelChanging(value);
					this.SendPropertyChanging();
					this._TelCel = value;
					this.SendPropertyChanged("TelCel");
					this.OnTelCelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(50)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Mercadoria")]
	public partial class Mercadoria : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idMercadoria;
		
		private string _Descricao;
		
		private string _ValorCusto;
		
		private System.Nullable<decimal> _ValorVenda;
		
		private int _QuantidadeEstoque;
		
		private string _Marca;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidMercadoriaChanging(int value);
    partial void OnidMercadoriaChanged();
    partial void OnDescricaoChanging(string value);
    partial void OnDescricaoChanged();
    partial void OnValorCustoChanging(string value);
    partial void OnValorCustoChanged();
    partial void OnValorVendaChanging(System.Nullable<decimal> value);
    partial void OnValorVendaChanged();
    partial void OnQuantidadeEstoqueChanging(int value);
    partial void OnQuantidadeEstoqueChanged();
    partial void OnMarcaChanging(string value);
    partial void OnMarcaChanged();
    #endregion
		
		public Mercadoria()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idMercadoria", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int idMercadoria
		{
			get
			{
				return this._idMercadoria;
			}
			set
			{
				if ((this._idMercadoria != value))
				{
					this.OnidMercadoriaChanging(value);
					this.SendPropertyChanging();
					this._idMercadoria = value;
					this.SendPropertyChanged("idMercadoria");
					this.OnidMercadoriaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descricao", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Descricao
		{
			get
			{
				return this._Descricao;
			}
			set
			{
				if ((this._Descricao != value))
				{
					this.OnDescricaoChanging(value);
					this.SendPropertyChanging();
					this._Descricao = value;
					this.SendPropertyChanged("Descricao");
					this.OnDescricaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ValorCusto", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string ValorCusto
		{
			get
			{
				return this._ValorCusto;
			}
			set
			{
				if ((this._ValorCusto != value))
				{
					this.OnValorCustoChanging(value);
					this.SendPropertyChanging();
					this._ValorCusto = value;
					this.SendPropertyChanged("ValorCusto");
					this.OnValorCustoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ValorVenda", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> ValorVenda
		{
			get
			{
				return this._ValorVenda;
			}
			set
			{
				if ((this._ValorVenda != value))
				{
					this.OnValorVendaChanging(value);
					this.SendPropertyChanging();
					this._ValorVenda = value;
					this.SendPropertyChanged("ValorVenda");
					this.OnValorVendaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QuantidadeEstoque", DbType="Int NOT NULL")]
		public int QuantidadeEstoque
		{
			get
			{
				return this._QuantidadeEstoque;
			}
			set
			{
				if ((this._QuantidadeEstoque != value))
				{
					this.OnQuantidadeEstoqueChanging(value);
					this.SendPropertyChanging();
					this._QuantidadeEstoque = value;
					this.SendPropertyChanged("QuantidadeEstoque");
					this.OnQuantidadeEstoqueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Marca", DbType="VarChar(50)")]
		public string Marca
		{
			get
			{
				return this._Marca;
			}
			set
			{
				if ((this._Marca != value))
				{
					this.OnMarcaChanging(value);
					this.SendPropertyChanging();
					this._Marca = value;
					this.SendPropertyChanged("Marca");
					this.OnMarcaChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.OrdemServico")]
	public partial class OrdemServico : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idOrdemServico;
		
		private string _Descricao;
		
		private System.DateTime _Data;
		
		private System.Nullable<System.DateTime> _DataEntrega;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidOrdemServicoChanging(int value);
    partial void OnidOrdemServicoChanged();
    partial void OnDescricaoChanging(string value);
    partial void OnDescricaoChanged();
    partial void OnDataChanging(System.DateTime value);
    partial void OnDataChanged();
    partial void OnDataEntregaChanging(System.Nullable<System.DateTime> value);
    partial void OnDataEntregaChanged();
    #endregion
		
		public OrdemServico()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idOrdemServico", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int idOrdemServico
		{
			get
			{
				return this._idOrdemServico;
			}
			set
			{
				if ((this._idOrdemServico != value))
				{
					this.OnidOrdemServicoChanging(value);
					this.SendPropertyChanging();
					this._idOrdemServico = value;
					this.SendPropertyChanged("idOrdemServico");
					this.OnidOrdemServicoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descricao", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Descricao
		{
			get
			{
				return this._Descricao;
			}
			set
			{
				if ((this._Descricao != value))
				{
					this.OnDescricaoChanging(value);
					this.SendPropertyChanging();
					this._Descricao = value;
					this.SendPropertyChanged("Descricao");
					this.OnDescricaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Data", DbType="Date NOT NULL")]
		public System.DateTime Data
		{
			get
			{
				return this._Data;
			}
			set
			{
				if ((this._Data != value))
				{
					this.OnDataChanging(value);
					this.SendPropertyChanging();
					this._Data = value;
					this.SendPropertyChanged("Data");
					this.OnDataChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataEntrega", DbType="Date")]
		public System.Nullable<System.DateTime> DataEntrega
		{
			get
			{
				return this._DataEntrega;
			}
			set
			{
				if ((this._DataEntrega != value))
				{
					this.OnDataEntregaChanging(value);
					this.SendPropertyChanging();
					this._DataEntrega = value;
					this.SendPropertyChanged("DataEntrega");
					this.OnDataEntregaChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TipoServico")]
	public partial class TipoServico : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idTipoServico;
		
		private string _Descricao;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidTipoServicoChanging(int value);
    partial void OnidTipoServicoChanged();
    partial void OnDescricaoChanging(string value);
    partial void OnDescricaoChanged();
    #endregion
		
		public TipoServico()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idTipoServico", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int idTipoServico
		{
			get
			{
				return this._idTipoServico;
			}
			set
			{
				if ((this._idTipoServico != value))
				{
					this.OnidTipoServicoChanging(value);
					this.SendPropertyChanging();
					this._idTipoServico = value;
					this.SendPropertyChanged("idTipoServico");
					this.OnidTipoServicoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descricao", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Descricao
		{
			get
			{
				return this._Descricao;
			}
			set
			{
				if ((this._Descricao != value))
				{
					this.OnDescricaoChanging(value);
					this.SendPropertyChanging();
					this._Descricao = value;
					this.SendPropertyChanged("Descricao");
					this.OnDescricaoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Fornecedor")]
	public partial class Fornecedor : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idFornecedor;
		
		private string _NomeFantasia;
		
		private string _RazaoSocial;
		
		private string _CNPJ;
		
		private string _Logradouro;
		
		private string _Bairro;
		
		private string _Cidade;
		
		private string _UF;
		
		private string _CEP;
		
		private string _TelRes;
		
		private string _TelCel;
		
		private string _email;
		
		private string _Pais;
		
		private string _Comentario;
		
		private string _InscricaoEstadual;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidFornecedorChanging(int value);
    partial void OnidFornecedorChanged();
    partial void OnNomeFantasiaChanging(string value);
    partial void OnNomeFantasiaChanged();
    partial void OnRazaoSocialChanging(string value);
    partial void OnRazaoSocialChanged();
    partial void OnCNPJChanging(string value);
    partial void OnCNPJChanged();
    partial void OnLogradouroChanging(string value);
    partial void OnLogradouroChanged();
    partial void OnBairroChanging(string value);
    partial void OnBairroChanged();
    partial void OnCidadeChanging(string value);
    partial void OnCidadeChanged();
    partial void OnUFChanging(string value);
    partial void OnUFChanged();
    partial void OnCEPChanging(string value);
    partial void OnCEPChanged();
    partial void OnTelResChanging(string value);
    partial void OnTelResChanged();
    partial void OnTelCelChanging(string value);
    partial void OnTelCelChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnPaisChanging(string value);
    partial void OnPaisChanged();
    partial void OnComentarioChanging(string value);
    partial void OnComentarioChanged();
    partial void OnInscricaoEstadualChanging(string value);
    partial void OnInscricaoEstadualChanged();
    #endregion
		
		public Fornecedor()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idFornecedor", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int idFornecedor
		{
			get
			{
				return this._idFornecedor;
			}
			set
			{
				if ((this._idFornecedor != value))
				{
					this.OnidFornecedorChanging(value);
					this.SendPropertyChanging();
					this._idFornecedor = value;
					this.SendPropertyChanged("idFornecedor");
					this.OnidFornecedorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NomeFantasia", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string NomeFantasia
		{
			get
			{
				return this._NomeFantasia;
			}
			set
			{
				if ((this._NomeFantasia != value))
				{
					this.OnNomeFantasiaChanging(value);
					this.SendPropertyChanging();
					this._NomeFantasia = value;
					this.SendPropertyChanged("NomeFantasia");
					this.OnNomeFantasiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RazaoSocial", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string RazaoSocial
		{
			get
			{
				return this._RazaoSocial;
			}
			set
			{
				if ((this._RazaoSocial != value))
				{
					this.OnRazaoSocialChanging(value);
					this.SendPropertyChanging();
					this._RazaoSocial = value;
					this.SendPropertyChanged("RazaoSocial");
					this.OnRazaoSocialChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CNPJ", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string CNPJ
		{
			get
			{
				return this._CNPJ;
			}
			set
			{
				if ((this._CNPJ != value))
				{
					this.OnCNPJChanging(value);
					this.SendPropertyChanging();
					this._CNPJ = value;
					this.SendPropertyChanged("CNPJ");
					this.OnCNPJChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Logradouro", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Logradouro
		{
			get
			{
				return this._Logradouro;
			}
			set
			{
				if ((this._Logradouro != value))
				{
					this.OnLogradouroChanging(value);
					this.SendPropertyChanging();
					this._Logradouro = value;
					this.SendPropertyChanged("Logradouro");
					this.OnLogradouroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bairro", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Bairro
		{
			get
			{
				return this._Bairro;
			}
			set
			{
				if ((this._Bairro != value))
				{
					this.OnBairroChanging(value);
					this.SendPropertyChanging();
					this._Bairro = value;
					this.SendPropertyChanged("Bairro");
					this.OnBairroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cidade", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Cidade
		{
			get
			{
				return this._Cidade;
			}
			set
			{
				if ((this._Cidade != value))
				{
					this.OnCidadeChanging(value);
					this.SendPropertyChanging();
					this._Cidade = value;
					this.SendPropertyChanged("Cidade");
					this.OnCidadeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UF", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string UF
		{
			get
			{
				return this._UF;
			}
			set
			{
				if ((this._UF != value))
				{
					this.OnUFChanging(value);
					this.SendPropertyChanging();
					this._UF = value;
					this.SendPropertyChanged("UF");
					this.OnUFChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CEP", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string CEP
		{
			get
			{
				return this._CEP;
			}
			set
			{
				if ((this._CEP != value))
				{
					this.OnCEPChanging(value);
					this.SendPropertyChanging();
					this._CEP = value;
					this.SendPropertyChanged("CEP");
					this.OnCEPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TelRes", DbType="VarChar(50)")]
		public string TelRes
		{
			get
			{
				return this._TelRes;
			}
			set
			{
				if ((this._TelRes != value))
				{
					this.OnTelResChanging(value);
					this.SendPropertyChanging();
					this._TelRes = value;
					this.SendPropertyChanged("TelRes");
					this.OnTelResChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TelCel", DbType="VarChar(50)")]
		public string TelCel
		{
			get
			{
				return this._TelCel;
			}
			set
			{
				if ((this._TelCel != value))
				{
					this.OnTelCelChanging(value);
					this.SendPropertyChanging();
					this._TelCel = value;
					this.SendPropertyChanged("TelCel");
					this.OnTelCelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(50)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pais", DbType="VarChar(50)")]
		public string Pais
		{
			get
			{
				return this._Pais;
			}
			set
			{
				if ((this._Pais != value))
				{
					this.OnPaisChanging(value);
					this.SendPropertyChanging();
					this._Pais = value;
					this.SendPropertyChanged("Pais");
					this.OnPaisChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comentario", DbType="VarChar(50)")]
		public string Comentario
		{
			get
			{
				return this._Comentario;
			}
			set
			{
				if ((this._Comentario != value))
				{
					this.OnComentarioChanging(value);
					this.SendPropertyChanging();
					this._Comentario = value;
					this.SendPropertyChanged("Comentario");
					this.OnComentarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InscricaoEstadual", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string InscricaoEstadual
		{
			get
			{
				return this._InscricaoEstadual;
			}
			set
			{
				if ((this._InscricaoEstadual != value))
				{
					this.OnInscricaoEstadualChanging(value);
					this.SendPropertyChanging();
					this._InscricaoEstadual = value;
					this.SendPropertyChanged("InscricaoEstadual");
					this.OnInscricaoEstadualChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
